### PR TITLE
compose file added

### PR DESCRIPTION
**Pull request by kdsinghcoder**
Fixed issue: #19

### CODE REVIEW

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
please add image / asciinema of commands running

**Comment by kdsinghcoder** [comment]
image

**Comment by kdsinghcoder** [comment]
image

@YashKumarVerma  image.

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
image
image

**Comment by YashKumarVerma** [comment]
updates ?

**Comment by YashKumarVerma** [comment]
is this even running?

image

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
syntax error

**Comment by YashKumarVerma** [comment]
thanks !

**Pull request merged**
