### PR TITLE
add password validation

### LINKED ISSUE #23: Add password strength checker
While creating an account, show the user if the password is weak. Use any well-known set of conditions like minimum length, a combination of upper case, lower case, etc.

### PR DESCRIPTION
**Pull request by kdsinghcoder**
fixes #23

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
please change the description to `fixes #{issue-number` to attach the issue

**Comment by kdsinghcoder** [comment]
> please change the description to `fixes #{issue-number` to attach the issue

@YashKumarVerma done, will keep this in mind from the next time.

**Comment by YashKumarVerma** [comment]
Looks dope, it'd be great if we add screenshots to PRs that affect the UI.

image
image

**Review by YashKumarVerma — APPROVED** [review]
LGTM

**Comment by YashKumarVerma** [comment]
Thank you for your contributions! This feature was really required.

**Pull request merged**
