### PR TITLE
copy to clipboard icon added

### LINKED ISSUE #20: Add `copy` feature in the application details
The current interface does not allow the user to copy the text directly. This is a heavily demanded feature. This can be done by adding a small copy button in the text field itself, towards the right side.

The copy button can be something like :

### PR DESCRIPTION
**Pull request by kdsinghcoder**
fixes #20 
image

image

Clipboard icons are added to the UI.

image

Favicon added

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
@kdsinghcoder can you add screenshots of the UI changes.

**Comment by kdsinghcoder** [comment]
Fixed issue:- https://github.com/UniAuth/uniauth-backend/issues/18

**Comment by YashKumarVerma** [comment]
> Fixed issue:- #18

please solve only 1 issue in 1 PR.

**Comment by YashKumarVerma** [comment]
Thank you for your contributions!

**Pull request merged**
