### PR TITLE
chore(docker): add ignore file, minor fixes

### LINKED ISSUE #112: Error in docker build
when running `docker build -t some name .` the build shows errors. These need to be fixed.

image

### PR DESCRIPTION
**Pull request by Aryaman1706**
# Issue Related with PR
- fixes #112 

# Proposed Changes
- Added a .dockerignore file to ignore node_modules and lock files.
- Used docker image node:lts-alpine3.10 to avoid incompatibilities of certain packages with npm version.

# Additional info if necessary
- I have commented out docker-compose as of now because docker command won't be present in the container. I thought it would be better if we discuss it before making further changes to dockerfile

# Checklist
- [-] Tests
- [-] Resolve Conflicts

# Screenshots
- None

### CODE REVIEW

**Review by YashKumarVerma — APPROVED** [review]
could you please post a screenshot of the containers running?

**Comment by Aryaman1706** [comment]
Sure @YashKumarVerma . Here they are-

Command:- docker build . -t uniauth
Screenshot:- 
build

Command:- docker run  --init -it uniauth
Screenshot:-
dockerrun

**Comment by Aryaman1706** [comment]
Hello @YashKumarVerma and team. If there are any concerns/issues regarding the PR, please do let me know. I would like to work towards its improvement.
Your feedback would be highly appreciated.

**Review by YashKumarVerma — APPROVED** [review]

**Comment by YashKumarVerma** [comment]
thanks !

**Pull request merged**
