### PR TITLE
chore(ci): integrated codecov coverage

### LINKED ISSUE #120: Integrate CodeCov Coverage Checks
codecov can be used to effectively check the code coverage on a pull requests and commits.

Some configurations need to be done to integrate it to monitor GitHub actions and generate reports.

you can read up more about sample implementation here:https://docs.codecov.io/docs/supported-languages

https://github.com/codecov/codecov-action

## Note
- we are using JEST
- we are using github actions

### PR DESCRIPTION
**Pull request by MASTERCHIEF011**
# Issue Related with PR
- fixes #120 

link to sample repo:
https://github.com/MASTERCHIEF011/codecov-node

### CODE REVIEW

**Comment by MASTERCHIEF011** [comment]
@YashKumarVerma  Pls check this out!

**Comment by YashKumarVerma** [comment]
where can i see the coverage in the sample repo ?

**Comment by MASTERCHIEF011** [comment]
> where can i see the coverage in the sample repo ?

in the bin folder in root directory

**Review by YashKumarVerma — APPROVED** [review]

**Comment by YashKumarVerma** [comment]
thanks !

**Pull request merged**
