### PR TITLE
chore(server): Logging to a file

### LINKED ISSUE #165: Write logs to file
The logs are being written to the console, but for them to be actually useful, we need them in a file so that they can be used later on.

Edit the logger configs to write the logs to file.

### PR DESCRIPTION
**Pull request by aniketbiswas21**
# Issue Related with PR
- fixes #165 

# Proposed Changes
- Configured Winston logger to log into files
- Classified error logs onto a separate file

# Additional info if necessary
- None

# Checklist
- [x] Configure Winston
- [x] Fix missing logs in controllers

### CODE REVIEW

**Comment by aniketbiswas21** [comment]
@YashKumarVerma Please take a look! Also I am not so sure about the hound reviews (' should be "). Can you help me with that?

**Comment by aniketbiswas21** [comment]
@YashKumarVerma Also, I think when an application is being created, there is a verbose log done. But, it is not logging. Can you help me with that? Although, validation error, etc seems to be logged and stored in file.

**Comment by YashKumarVerma** [comment]
I have just disabled hound so those issues can be disabled.

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma Also, I think when an application is being created, there is a verbose log done. But, it is not logging. Can you help me with that? Although, validation error, etc seems to be logged and stored in file.

it's fine is the logs of application start are not visible as of now.

**Comment by aniketbiswas21** [comment]
> > @YashKumarVerma Also, I think when an application is being created, there is a verbose log done. But, it is not logging. Can you help me with that? Although, validation error, etc seems to be logged and stored in file.
> 
> it's fine is the logs of application start are not visible as of now.

Whatever logs are being done inside controllers are not visible. I get the logs when the nest application starts. Also, when there is an error thrown say, when I fill the wrong data while creating an application, it gets logged.

**Comment by YashKumarVerma** [comment]
> > > @YashKumarVerma Also, I think when an application is being created, there is a verbose log done. But, it is not logging. Can you help me with that? Although, validation error, etc seems to be logged and stored in file.
> > 
> > 
> > it's fine is the logs of application start are not visible as of now.
> 
> Whatever logs are being done inside controllers are not visible. I get the logs when the nest application starts. Also, when there is an error thrown say, when I fill the wrong data while creating an application, it gets logged.

not very sure of this, but can the logging level be a reason for this? When application starts and controllers run, it's usually a `logger.verbose` that's running.

When an error is thrown, it's `logger.error`, and if you see the configs, .error has a higher preference than .verbose

**Comment by aniketbiswas21** [comment]
@YashKumarVerma I have fixed all the errors. Can you review my pr?

**Comment by YashKumarVerma** [comment]
image
There's this small issue, the verbose.log, the info logs are also there. This can be resolved in a further issue. Good work with this one.

**Review by YashKumarVerma — APPROVED** [review]

**Comment by YashKumarVerma** [comment]
thanks !

**Comment by aniketbiswas21** [comment]
> image
> There's this small issue, the verbose.log, the info logs are also there. This can be resolved in a further issue. Good work with this one.

I can work on this. But, I wasn't able to figure it out at the time because specifying verbose as a level meant verbose and all the other levels that are lower in order were getting logged. Couldn't figure out a way to lock that to a particular level only

**Comment by aniketbiswas21** [comment]
> thanks !

Glad I could contribute :smile:  Learning a lot from this :sweat_smile:

**Pull request merged**
