### PR TITLE
List of  applications having access to user data.

### LINKED ISSUE #16: Show list of applications that have user's data
Currently, the user can see only the number of applications that have got access to users data. We need to display the application along with the details that are shared with them. 

Steps:
The controller has user data. Just get details of the mongoose subdocument, and render it

### PR DESCRIPTION
**Pull request by tanay13**
Fixes #16 

uniauth

### CODE REVIEW

**Comment by tanay13** [comment]
@YashKumarVerma Please review this

**Comment by YashKumarVerma** [comment]
Could you show the support email and scopes as well?

**Comment by tanay13** [comment]
uniauth1
@YashKumarVerma Is this fine?

**Review by YashKumarVerma — APPROVED** [review]
LGTM !

**Comment by YashKumarVerma** [comment]
also, we can use `fixes #{issue-number}` to attach issues to PR.

**Comment by YashKumarVerma** [comment]
Thanks for your contributions!

🥳

**Pull request merged**
