### PR TITLE
Integrated CodeCov coverage checks

### LINKED ISSUE #120: Integrate CodeCov Coverage Checks
codecov can be used to effectively check the code coverage on a pull requests and commits.

Some configurations need to be done to integrate it to monitor GitHub actions and generate reports.

you can read up more about sample implementation here:https://docs.codecov.io/docs/supported-languages

https://github.com/codecov/codecov-action

## Note
- we are using JEST
- we are using github actions

### PR DESCRIPTION
**Pull request by MASTERCHIEF011**
# Issue Related with PR
- fixes #120 

# Proposed Changes
- Setup workflow.yml for CodeCov

### CODE REVIEW

**Comment by MASTERCHIEF011** [comment]
This is just a basic setup of CodeCov.

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
add sample repository where this config works

**Comment by MASTERCHIEF011** [comment]
> add sample repository where this config works

okay

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
you do not have to add a sample repo in this project, add it to ur personal account and share link.

**Pull request closed without merging**
